FROM eclipse-temurin:22-jdk-jammy as builder

WORKDIR /app
COPY . .
RUN ./mvnw package
FROM eclipse-temurin:22-jdk-jammy
WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]